services:
  auditing_harness:
    image: prism-test/harness
    container_name: auditing_harness
    volumes:
      - auditing_harness:/opt/prism/cache
      - ./harness/app/bin:/opt/prism/bin
      - ./eval/auditing/logs:/opt/prism/logs
      - ./eval/eval-auditing.sh:/opt/prism/eval-auditing.sh
    env_file:
      - ./cache/accounts.env
    command: /opt/prism/eval-auditing.sh

volumes:
  auditing_harness:
