services:
  gentags_harness:
    image: prism-test/harness
    container_name: gentags_harness
    volumes:
      - gentags_harness:/opt/prism/cache
      - ./harness/app/bin:/opt/prism/bin
      - ./eval/gentags/logs:/opt/prism/logs
      - ./eval/eval-gentags.sh:/opt/prism/eval-gentags.sh
    env_file:
      - ./cache/accounts.env
    command: /opt/prism/eval-gentags.sh

volumes:
  gentags_harness:
