services:
  frequency_harness0.1:
    image: prism-test/harness
    container_name: frequency_harness0.1
    volumes:
      - harness0.1:/opt/prism/cache
      - ./harness/app/bin:/opt/prism/bin
      - ./eval/frequency/logs:/opt/prism/logs
      - ./eval/eval-frequency.sh:/opt/prism/eval-frequency.sh
    env_file:
      - accounts.env
    profiles:
      - "0.1"
      - all
    command: /opt/prism/eval-frequency.sh 0.1

  frequency_harness0.3:
    image: prism-test/harness
    container_name: frequency_harness0.3
    volumes:
      - harness0.3:/opt/prism/cache
      - ./harness/app/bin:/opt/prism/bin
      - ./eval/frequency/logs:/opt/prism/logs
      - ./eval/eval-frequency.sh:/opt/prism/eval-frequency.sh
    env_file:
      - accounts.env
    profiles:
      - "0.3"
      - all
    command: /opt/prism/eval-frequency.sh 0.3

  frequency_harness0.5:
    image: prism-test/harness
    container_name: frequency_harness0.5
    volumes:
      - harness0.5:/opt/prism/cache
      - ./harness/app/bin:/opt/prism/bin
      - ./eval/frequency/logs:/opt/prism/logs
      - ./eval/eval-frequency.sh:/opt/prism/eval-frequency.sh
    env_file:
      - accounts.env
    profiles:
      - "0.5"
      - all
    command: /opt/prism/eval-frequency.sh 0.5

  frequency_harness0.7:
    image: prism-test/harness
    container_name: frequency_harness0.7
    volumes:
      - harness0.7:/opt/prism/cache
      - ./harness/app/bin:/opt/prism/bin
      - ./eval/frequency/logs:/opt/prism/logs
      - ./eval/eval-frequency.sh:/opt/prism/eval-frequency.sh
    env_file:
      - accounts.env
    profiles:
      - "0.7"
      - all
    command: /opt/prism/eval-frequency.sh 0.7

  frequency_harness0.9:
    image: prism-test/harness
    container_name: frequency_harness0.9
    volumes:
      - harness0.9:/opt/prism/cache
      - ./harness/app/bin:/opt/prism/bin
      - ./eval/frequency/logs:/opt/prism/logs
      - ./eval/eval-frequency.sh:/opt/prism/eval-frequency.sh
    env_file:
      - accounts.env
    profiles:
      - "0.9"
      - all
    command: /opt/prism/eval-frequency.sh 0.9

volumes:
  harness0.1:
  harness0.3:
  harness0.5:
  harness0.7:
  harness0.9:
