services:
  testnet:
    image: prism/prism-sol
    container_name: contract_testnet
    hostname: testnet
    ports:
      - 8545:8545
    command: start

  harness:
    image: prism-test/harness
    container_name: contract_harness
    volumes:
      - harness:/opt/prism/cache
      - ./cache/contract-addr.env:/opt/prism/contract-addr.env
      - ./harness/app/bin:/opt/prism/bin
      - ./eval/contract/logs:/opt/prism/logs
      - ./eval/eval-contract.sh:/opt/prism/eval-contract.sh
    env_file:
      - ./cache/accounts.env
    command: /opt/prism/eval-contract.sh

volumes:
  harness:
