services:
  testnet:
    image: dpduado-test/testnet
    build: ./testnet/build
    hostname: testnet
    volumes:
      - ./testnet/dpduado-sol:/app
    environment:
      - RPC_HOST=0.0.0.0
      - RPC_PORT=8545
      - NUM_FIRST_ACCOUNTS=1
      - BALANCE_FIRST_ACCOUNTS=300
      - WALLET_MNEMONIC=chaos knee unit sing method banana chicken quote script boat crouch pig
    ports:
      - 8545:8545
    command: start

  harness:
    image: dpduado-test/harness
    build:
      context: ./harness
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    container_name: harness
    hostname: harness
    volumes:
      - ./harness/app:/app
