services:
  harness0.2:
    image: dpduado-test/harness
    container_name: harness0.2
    volumes:
      - harness0.2:/opt/dpduado/cache
      - ./harness/app/bin:/opt/dpduado/bin
      - ./eval/frequency/logs:/opt/dpduado/logs
      - ./eval/eval-frequency.sh:/opt/dpduado/eval-frequency.sh
    env_file:
      - accounts.env
    profiles:
      - "0.2"
      - all
    command: /opt/dpduado/eval-frequency.sh 0.2

  harness0.4:
    image: dpduado-test/harness
    container_name: harness0.4
    volumes:
      - harness0.4:/opt/dpduado/cache
      - ./harness/app/bin:/opt/dpduado/bin
      - ./eval/frequency/logs:/opt/dpduado/logs
      - ./eval/eval-frequency.sh:/opt/dpduado/eval-frequency.sh
    env_file:
      - accounts.env
    profiles:
      - "0.4"
      - all
    command: /opt/dpduado/eval-frequency.sh 0.4

  harness0.6:
    image: dpduado-test/harness
    container_name: harness0.6
    volumes:
      - harness0.6:/opt/dpduado/cache
      - ./harness/app/bin:/opt/dpduado/bin
      - ./eval/frequency/logs:/opt/dpduado/logs
      - ./eval/eval-frequency.sh:/opt/dpduado/eval-frequency.sh
    env_file:
      - accounts.env
    profiles:
      - "0.6"
      - all
    command: /opt/dpduado/eval-frequency.sh 0.6

  harness0.8:
    image: dpduado-test/harness
    container_name: harness0.8
    volumes:
      - harness0.8:/opt/dpduado/cache
      - ./harness/app/bin:/opt/dpduado/bin
      - ./eval/frequency/logs:/opt/dpduado/logs
      - ./eval/eval-frequency.sh:/opt/dpduado/eval-frequency.sh
    env_file:
      - accounts.env
    profiles:
      - "0.8"
      - all
    command: /opt/dpduado/eval-frequency.sh 0.8

  harness1.0:
    image: dpduado-test/harness
    container_name: harness1.0
    volumes:
      - harness1.0:/opt/dpduado/cache
      - ./harness/app/bin:/opt/dpduado/bin
      - ./eval/frequency/logs:/opt/dpduado/logs
      - ./eval/eval-frequency.sh:/opt/dpduado/eval-frequency.sh
    env_file:
      - accounts.env
    profiles:
      - "1.0"
      - all
    command: /opt/dpduado/eval-frequency.sh 1.0

volumes:
  harness0.2:
  harness0.4:
  harness0.6:
  harness0.8:
  harness1.0:
