services:
  testnet:
    image: prism/prism-sol
    hostname: testnet
    ports:
      - 8545:8545
    command: start

  harness:
    image: prism-test/harness
    container_name: harness
    hostname: harness
    volumes:
      - ./harness/volume:/var/lib/prism-harness
      - go_cache:/root/.cache/go-build
    env_file:
      - ./cache/accounts.env

volumes:
  go_cache:
