services:
  testnet:
    image: prism-test/testnet
    container_name: contract_testnet
    hostname: testnet
    volumes:
      - ./testnet/prism-sol:/app
    environment:
      - BALANCE_FIRST_ACCOUNTS=300
      - WALLET_MNEMONIC=chaos knee unit sing method banana chicken quote script boat crouch pig
    env_file:
      - ./cache/accounts.env
    ports:
      - 8545:8545
    command: start

  harness:
    image: prism-test/harness
    container_name: contract_harness
    volumes:
      - harness:/opt/prism/cache
      - ./cache/contract-addr.env:/opt/prism/contract-addr.env
      - ./harness/app/bin:/opt/prism/bin
      - ./eval/contract/logs:/opt/prism/logs
      - ./eval/eval-contract.sh:/opt/prism/eval-contract.sh
    env_file:
      - ./cache/accounts.env
    command: /opt/prism/eval-contract.sh

volumes:
  harness:
